export const SET_APP_NOTIFICATION = 'SET_APP_NOTIFICATION';
export const SET_ERROR_NOTIFICATION = 'SET_ERROR_NOTIFICATION'
export const CLEAR_APP_NOTIFICATION = 'CLEAR_APP_NOTIFICATION'
export const CLEAR_ERROR_NOTIFICATION = 'CLEAR_ERROR_NOTIFICATION';